// export const ASSETS_HOST = "http://static.guxiaohui.com/act-lbs-new/"
export const ASSETS_HOST =
  'https://qrmkt.oss-cn-beijing.aliyuncs.com/common/jihe2021/hthj/'

export const IMAGE_RESOURCES = {
  bgActRule: 'lbs-bg-act-rule1.png',
  bgPkSuccess: 'lbs-bg-pk-success1.png',
  btnKnown: 'lbs-btn-known1.png',
  iconCloth: 'lbs-icon-cloth.png',
  iconStoneCircle: 'lbs-icon-stone-circle.png',
  bgChooseGuesture: 'lbs-bg-choose-guesture.png',
  bgPkXianziFail: 'lbs-bg-pk-xianzi-fail1.png',
  btnKuaisuxunhe: 'lbs-btn-kuaisuxunhe.png',
  iconHebao: 'lbs-icon-hebao.png',
  iconStone: 'lbs-icon-stone.png',
  bgConfirm: 'lbs-bg-confirm.png',
  bgPkerInfo: 'lbs-bg-pker-info1.png',
  btnPkSoon: 'lbs-btn-pk-soon1.png',
  iconHedian: 'lbs-icon-hedian.png',
  iconVs: 'lbs-icon-vs1.png',
  bgGameHistory: 'lbs-bg-game-history1.png',
  bgXianzi: 'lbs-bg-xianzi.png',
  btnRule: 'lbs-btn-rule.png',
  iconMarkerHebao: 'lbs-icon-marker-hebao.png',
  iconXianzi: 'lbs-icon-xianzi1.png',
  bgGetHebao: 'lbs-bg-get-hebao1.png',
  btnConfirm: 'lbs-btn-confirm1.png',
  btnShanghezhongguoxing: 'lbs-btn-shanghezhongguoxing.png',
  iconPkerLeft: 'lbs-icon-pker-left1.png',
  markerPk: 'lbs-marker-pk2.png',
  bgHedianGet: 'lbs-bg-hedian-get1.png',
  btnGameHistory: 'lbs-btn-game-history1.png',
  btnSubmit: 'lbs-btn-submit1.png',
  iconPkerRight: 'lbs-icon-pker-right1.png',
  markerShop: 'lbs-marker-shop2.png',
  bgHedianGot: 'lbs-bg-hedian-got1.png',
  btnGetQuick: 'lbs-btn-get-quick1.png',
  btnGetQuick2: 'lbs-btn-get-quick2.png',
  iconAvatarDefault: 'lbs-icon-avatar-default.png',
  iconSisorsCircle: 'lbs-icon-sisors-circle.png',
  pkBg: 'lbs-pk-bg.jpg',
  bgPkFail: 'lbs-bg-pk-fail1.png',
  btnHejiaGift: 'lbs-btn-hejia-gift.png',
  iconCloseGreen: 'lbs-icon-close-green.png',
  iconSisors: 'lbs-icon-sisors.png',
  bgPkRule: 'lbs-bg-pk-rule1.png',
  btnJoin: 'lbs-btn-join1.png',
  iconClothCircle: 'lbs-icon-cloth-circle.png',
  iconStart: 'lbs-icon-start.png',
  iconRefresh: 'lbs-icon-refresh.png',
  iconClose: 'lbs-icon-close.png',
  btnMyPk: 'lbs-btn-my-pk1.png',
  btnMyPkActive: 'lbs-btn-my-pk-active1.png',
  btnMyChallenge: 'lbs-btn-my-challenge1.png',
  btnMyChallengeActive: 'lbs-btn-my-challenge-active1.png',
  bgChooseGestrue: 'lbs-bg-choose-guesture1.png',
  iconRadio: 'lbs-icon-radio1.png',
  iconRadioActive: 'lbs-icon-radio-active1.png',
  iconWechat: 'lbs-icon-wechat.png',
  markerXianzi: 'lbs-marker-xianzi.png',
  iconPlusWhite: 'lbs-icon-plus-white.png',
  iconPlus: 'lbs-icon-plus1.png',
  bgNoAward: 'lbs-bg-no-award1.png',
  bgHebaoDetail: 'lbs-bg-hebao-detail.png',
  btnHebaoDetail: 'lbs-btn-hebao-detail.png',
  btnHedianDetail: 'lbs-btn-hedian-detail1.png',
  bgHedianDetail: 'lbs-bg-hedian-detail1.png',
  textPkChooseTips: 'lbs-text-pk-choose-tips.png',
  gestrueStoneLeft: 'lbs-gestrue-stone-left1.png',
  gestrueStoneRight: 'lbs-gestrue-stone-right1.png',
  gestrueScissorsLeft: 'lbs-gestrue-scissors-left1.png',
  gestrueScissorsRight: 'lbs-gestrue-scissors-right1.png',
  gestrueClothLeft: 'lbs-gestrue-cloth-left1.png',
  gestrueClothRight: 'lbs-gestrue-cloth-right1.png',
  iconLocationGreen: 'lbs-icon-location-green.png',
  btnKnowDraw: 'lbs-btn-know-draw1.png',
  bgToast: 'lbs-bg-toast.png',
  iconChooseGestureSissors: 'lbs-icon-choose-gesture-sissors1.png',
  iconChooseGestureStone: 'lbs-icon-choose-gesture-stone1.png',
  iconChooseGestureCloth: 'lbs-icon-choose-gesture-cloth1.png',
  bgNianhuo: 'lbs-bg-nianhuo.png',
  lbsTextSuccess: 'lbs-text-pk-success.png',
  bgPkAwardTextSmall: 'lbs-bg-pk-award-text-small.png',
  bgPkAwardText: 'lbs-bg-pk-award-text.png',
  iconHeqi: 'lbs-icon-heqi1.png',
  bgPatchShine: 'lbs-bg-patch-shine.png',
  materialPkTop: 'lbs-material-pk-top.png',
  materialPkBottom: 'lbs-material-pk-bottom.png',
  bgPk: 'lbs-bg-pk1.png',
  bgChooseNianhuo: 'lbs-bg-choose-nianhuo1.png',
  btnChooseNianhuo: 'lbs-btn-choose-nianhuo1.png',
  btnPkLatter: 'lbs-btn-pk-latter1.png',
  textChooseNianhuo: 'lbs-text-choose-nianhuo.png',
  textChooseGesture: 'lbs-text-choose-gesture.png',
  btnNianhuoPkSoon: 'lbs-nianhuo-pk-soon1.png',
  btnPkLatterNianhuo: 'btn-pk-latter-nianhuo1.png',
  lbsTipsXianzi: 'lbs-tips-xianzi.png',
  lbsXianziPkBg: 'lbs-xianzi-pk-bg.png'
}

export function getImage(key: string) {
  return ASSETS_HOST + IMAGE_RESOURCES[key] + '?v=3.917'
}
